default_stages: [pre-commit, pre-push]

repos:
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        args: ["--target-version", "py311"]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.4
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --show-fixes]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        args: [--strict]
        additional_dependencies:
          - types-setuptools
          - tokenize-rt==3.2.0
          - pytest==7.1
          - importlib_metadata
          - typing-extensions>=4.5
          - rich

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: debug-statements

  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: 1.7.0
    hooks:
      - id: pyproject-fmt
        exclude: docs/examples/