name: CI

on:
  push:
    branches:
      - main
      - 'temp-*'
      - 'feature/*'
      - 'bugfix/*'
  pull_request:
    branches:
      - main
      - 'temp-*'
      - 'feature/*'
      - 'bugfix/*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.11', '3.12' ]
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip/setuptools/wheel
        run: |
          pip install --upgrade pip setuptools wheel

      - name: Install dev extras
        run: |
          pip install -r requirements-dev.txt

      - name: Run Pre-commit
        run: |
          pip install pre-commit
          pre-commit run --all-files

      - name: Run Tox
        run: |
          pip install tox
          tox
