name: CI

on:
  push:
    branches:
      - main
      - 'temp-*'
      - 'feature/*'
      - 'bugfix/*'
  pull_request:
    branches:
      - main
      - 'temp-*'
      - 'feature/*'
      - 'bugfix/*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Upgrade pip/setuptools/wheel
        run: |
          pip install --upgrade pip setuptools wheel

      - name: Install dev extras
        run: |
          pip install .[dev]

      - name: Run Pre-commit
        run: |
          pip install pre-commit
          pre-commit run --all-files

      - name: Install Tox
        run: pip install tox

      - name: Run Tox
        run: tox  # This will execute tests for py311, py312
