name: Extract Release Notes Only

on:
  push:
    tags:
      - 'v*.*.*'  

jobs:
  extract_notes_job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Extract release notes
        run: |
          VERSION="${GITHUB_REF_NAME}"
          echo "Version is: $VERSION"

          # Step A: Convert any Windows line endings to Unix (optional, but prevents mismatch)
          sudo apt-get update
          sudo apt-get install -y dos2unix
          dos2unix CHANGELOG.md

          # Step B: Print from the line matching "## v0.1.0" (for example)
          #         until the next heading "## " or EOF.
          #         If your headings use EXACT format "## v0.1.0" with NO trailing space, this should match.
          sed -n "/^## $VERSION$/,/^## /p" CHANGELOG.md > extracted_notes.txt

          # Step C: Remove the first line (the heading itself)
          sed -i '1d' extracted_notes.txt

          # Step D: Remove any heading lines that might have been included (the next heading)
          sed -i '/^## /d' extracted_notes.txt

          echo "=== Extracted release notes for $VERSION ==="
          cat extracted_notes.txt
          echo "==========================================="
