name: Create Release from Changelog

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Extract Release Notes
        run: |
          VERSION="${GITHUB_REF_NAME}"        # e.g. 'v0.1.1'
          sed -n "/^$VERSION$/,/^v[0-9]*\.[0-9]*\.[0-9]*/p" CHANGELOG.md \
            | sed '$d' \
            | sed '1d' \
            > release_notes_extract.md

          # Explanation of the sed pipeline:
          # -  The first sed command prints everything from a line matching ^v0.1.1$
          #    until the next line that matches a version pattern ^vX.Y.Z,
          #    effectively grabbing just the text for v0.1.1.
          # -  Then we remove the last line (which might be the next version header).
          # -  Then we remove the first line (the heading itself).
          # -  Adjust to your exact headings or version pattern as needed.

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          name: "Release ${{ github.ref_name }}"
          bodyFile: "release_notes_extract.md"
          draft: false
          prerelease: false
