name: Build & Release
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Build (example)
        run: echo "Do your build or packaging here"

      # 1) Parse the changelog to extract only the new version’s notes
      - name: Extract release notes
        id: extract_notes
        run: |
          VERSION="${GITHUB_REF_NAME}"  # e.g. "v0.1.1"
          # Let's assume your version headings are formatted like "## v0.1.1"
          # Adjust sed patterns to match your real headings:
          sed -n "/^## $VERSION$/,/^## v[0-9]*\.[0-9]*\.[0-9]*/p" CHANGELOG.md \
            | sed '1d' \
            | sed '$d' \
            > extracted_notes.txt

          # Optionally cat it for debugging
          echo "--- Extracted release notes for $VERSION ---"
          cat extracted_notes.txt
          echo "-------------------------------------------"

          # Make them available as a step output
          echo "::set-output name=notes::$(cat extracted_notes.txt | sed 's/%/%25/g; s/\r/%0D/g; s/\n/%0A/g')"

      # 2) Create the release, using the extracted notes as the body
      - name: Create GitHub Release
        uses: actions/create-release@v1.1.4
        with:
          tag_name: ${{ github.ref_name }}
          release_name: "Release ${{ github.ref_name }}"
          body: ${{ steps.extract_notes.outputs.notes }}
          draft: false
          prerelease: ${{ contains(github.ref_name, 'rc') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
