name: Release to Test PyPI

on:
  push:
    branches: [ "test" ]
  
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install build python-semantic-release

      - name: Run Semantic Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          PYPI_USERNAME: "__token__"
          PYPI_PASSWORD: ${{ secrets.TEST_PYPI_TOKEN }}
          SEMANTIC_RELEASE_LEVEL: "minor"  # or "patch", or "major"


        run: semantic-release -vv publish
