name: Minimal OIDC Release

on:
  push:
    # Trigger only when pushing tags like v1.2.3
    # Adjust the pattern if you want other forms (e.g. rc, post, etc.)
    tags:
      - "v[0-9]+\\.[0-9]+\\.[0-9]+"

jobs:
  publish:
    runs-on: ubuntu-latest

    # Required for PyPI Trusted Publishing:
    permissions:
      id-token: write

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install build tool
        run: |
          pip install --upgrade pip
          pip install build

      - name: Build package
        run: python -m build
        # This creates dist/your_project-<version>.tar.gz and .whl

      - name: Publish to Test PyPI (OIDC)
        uses: pypa/gh-action-pypi-publish@release/v1
        # Notice: no user/password => uses OIDC
        with:
          repository-url: "https://test.pypi.org/legacy/"
