name: Minimal OIDC Release

on:
  push:
    tags:
      - "[0-9]+\\.[0-9]+\\.[0-9]+"
      - "[0-9]+\\.[0-9]+\\.[0-9]+.post[0-9]+"
      - "[0-9]+\\.[0-9]+\\.[0-9]+[a-b][0-9]+"  
      - "[0-9]+\\.[0-9]+\\.[0-9]+rc[0-9]+"  

jobs:
  build:
    name: Build the source tarball and the wheel
    runs-on: ubuntu-latest
    environment: release #?
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install build

      - name: Create packages
        run: pythin -m build

      - name: Verify build output
        run: ls -l dist/ || exit 1

      - name: Archive packages
        uses: actions/upload-artifact@v4
        with: python-dist
        parth: dist  



  publish:

    name: Publish build artifacts to the PyPI
    needs: build
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
      - name: Retrieve packages
        uses: actions/download-artifact@v4
        with:
          name: python-dist
          path: dist
      
      - name: Verify downloaded packages
        run: ls -l dist/ || exit 1

      - name: Publish to Test PyPI (OIDC)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: "https://test.pypi.org/legacy/"
