name: Publish packages to PyPI

on:
  push:
    tags:
      - "[0-9]+\\.[0-9]+\\.[0-9]+"
      - "[0-9]+\\.[0-9]+\\.[0-9]+.post[0-9]+"
      - "[0-9]+\\.[0-9]+\\.[0-9]+[a-b][0-9]+"  # e.g., 1.0.0a1, 1.0.0b2
      - "[0-9]+\\.[0-9]+\\.[0-9]+rc[0-9]+"  # e.g., 1.0.0rc1

jobs:
  build:
    name: Build the source tarball and the wheel
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install build

      - name: Create packages
        run: python -m build

      - name: Verify build output
        run: ls -l dist/ || exit 1  # Fail if no files are built

      - name: Archive packages
        uses: actions/upload-artifact@v4
        with:
          name: python-dist
          path: dist

  publish:
    name: Publish build artifacts to the PyPI
    needs: build
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write  # ✅ Needed for Trusted Publishing
    steps:
      - name: Retrieve packages
        uses: actions/download-artifact@v4
        with:
          name: python-dist
          path: dist  # ✅ Ensure packages go into 'dist/'

      - name: Verify downloaded packages
        run: ls -l dist/ || exit 1  # ✅ Debug if 'dist/' is empty

      - name: Upload packages to PyPI (Trusted Publishing)
        uses: pypa/gh-action-pypi-publish@release/v1
        # ✅ No 'user' or 'password' needed since OIDC is used

  release:
    name: Create a GitHub release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - id: changelog
        uses: agronholm/release-notes@v1
        with:
          path: docs/versionhistory.rst

      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changelog }}
