name: Semantic Release

on:
  push:
    branches: [ "test" ]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0    # Important: fetch all commit history and tags


      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install python-semantic-release
          pip install build
      
      - name: Build the package
        run: python -m build

      - name: Run Semantic Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

          PYPI_USERNAME: "__token__"
          PYPI_PASSWORD: ${{ secrets.TEST_PYPI_TOKEN }}

        run: semantic-release -vv publish
